[phases.setup]
nixPkgs = ["python310", "ffmpeg-full", "fontconfig", "freetype"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "gunicorn api_n8n_with_reciter-4:app --bind 0.0.0.0:$PORT --timeout 600 --workers 2"
